// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: callback_service.proto

package sdk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 聊天事件
type ChatEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallbackId uint32 `protobuf:"varint,1,opt,name=callback_id,json=callbackId,proto3" json:"callback_id,omitempty"`
	Sender     string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Message    string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ChatEventRequest) Reset() {
	*x = ChatEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEventRequest) ProtoMessage() {}

func (x *ChatEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callback_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEventRequest.ProtoReflect.Descriptor instead.
func (*ChatEventRequest) Descriptor() ([]byte, []int) {
	return file_callback_service_proto_rawDescGZIP(), []int{0}
}

func (x *ChatEventRequest) GetCallbackId() uint32 {
	if x != nil {
		return x.CallbackId
	}
	return 0
}

func (x *ChatEventRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatEventRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChatEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cancel bool `protobuf:"varint,1,opt,name=cancel,proto3" json:"cancel,omitempty"` // 是否取消事件传播
}

func (x *ChatEventResponse) Reset() {
	*x = ChatEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEventResponse) ProtoMessage() {}

func (x *ChatEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_callback_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEventResponse.ProtoReflect.Descriptor instead.
func (*ChatEventResponse) Descriptor() ([]byte, []int) {
	return file_callback_service_proto_rawDescGZIP(), []int{1}
}

func (x *ChatEventResponse) GetCancel() bool {
	if x != nil {
		return x.Cancel
	}
	return false
}

// 玩家事件
type PlayerEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallbackId uint32 `protobuf:"varint,1,opt,name=callback_id,json=callbackId,proto3" json:"callback_id,omitempty"`
	RawData    []byte `protobuf:"bytes,2,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"` // protocol.packet.PlayerListEntry 序列化数据
}

func (x *PlayerEventRequest) Reset() {
	*x = PlayerEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEventRequest) ProtoMessage() {}

func (x *PlayerEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callback_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEventRequest.ProtoReflect.Descriptor instead.
func (*PlayerEventRequest) Descriptor() ([]byte, []int) {
	return file_callback_service_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerEventRequest) GetCallbackId() uint32 {
	if x != nil {
		return x.CallbackId
	}
	return 0
}

func (x *PlayerEventRequest) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type PlayerEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PlayerEventResponse) Reset() {
	*x = PlayerEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEventResponse) ProtoMessage() {}

func (x *PlayerEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_callback_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEventResponse.ProtoReflect.Descriptor instead.
func (*PlayerEventResponse) Descriptor() ([]byte, []int) {
	return file_callback_service_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 数据包事件
type PacketEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallbackId uint32 `protobuf:"varint,1,opt,name=callback_id,json=callbackId,proto3" json:"callback_id,omitempty"`
	PacketId   uint32 `protobuf:"varint,2,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	PacketData []byte `protobuf:"bytes,3,opt,name=packet_data,json=packetData,proto3" json:"packet_data,omitempty"` // packet 序列化数据
}

func (x *PacketEventRequest) Reset() {
	*x = PacketEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketEventRequest) ProtoMessage() {}

func (x *PacketEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callback_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketEventRequest.ProtoReflect.Descriptor instead.
func (*PacketEventRequest) Descriptor() ([]byte, []int) {
	return file_callback_service_proto_rawDescGZIP(), []int{4}
}

func (x *PacketEventRequest) GetCallbackId() uint32 {
	if x != nil {
		return x.CallbackId
	}
	return 0
}

func (x *PacketEventRequest) GetPacketId() uint32 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

func (x *PacketEventRequest) GetPacketData() []byte {
	if x != nil {
		return x.PacketData
	}
	return nil
}

type PacketEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PacketEventResponse) Reset() {
	*x = PacketEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketEventResponse) ProtoMessage() {}

func (x *PacketEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_callback_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketEventResponse.ProtoReflect.Descriptor instead.
func (*PacketEventResponse) Descriptor() ([]byte, []int) {
	return file_callback_service_proto_rawDescGZIP(), []int{5}
}

func (x *PacketEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 预加载事件
type PreloadEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallbackId uint32 `protobuf:"varint,1,opt,name=callback_id,json=callbackId,proto3" json:"callback_id,omitempty"`
}

func (x *PreloadEventRequest) Reset() {
	*x = PreloadEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreloadEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreloadEventRequest) ProtoMessage() {}

func (x *PreloadEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callback_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreloadEventRequest.ProtoReflect.Descriptor instead.
func (*PreloadEventRequest) Descriptor() ([]byte, []int) {
	return file_callback_service_proto_rawDescGZIP(), []int{6}
}

func (x *PreloadEventRequest) GetCallbackId() uint32 {
	if x != nil {
		return x.CallbackId
	}
	return 0
}

type PreloadEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *PreloadEventResponse) Reset() {
	*x = PreloadEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreloadEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreloadEventResponse) ProtoMessage() {}

func (x *PreloadEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_callback_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreloadEventResponse.ProtoReflect.Descriptor instead.
func (*PreloadEventResponse) Descriptor() ([]byte, []int) {
	return file_callback_service_proto_rawDescGZIP(), []int{7}
}

func (x *PreloadEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PreloadEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 激活事件
type ActiveEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallbackId uint32 `protobuf:"varint,1,opt,name=callback_id,json=callbackId,proto3" json:"callback_id,omitempty"`
}

func (x *ActiveEventRequest) Reset() {
	*x = ActiveEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActiveEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveEventRequest) ProtoMessage() {}

func (x *ActiveEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callback_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveEventRequest.ProtoReflect.Descriptor instead.
func (*ActiveEventRequest) Descriptor() ([]byte, []int) {
	return file_callback_service_proto_rawDescGZIP(), []int{8}
}

func (x *ActiveEventRequest) GetCallbackId() uint32 {
	if x != nil {
		return x.CallbackId
	}
	return 0
}

type ActiveEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ActiveEventResponse) Reset() {
	*x = ActiveEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActiveEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveEventResponse) ProtoMessage() {}

func (x *ActiveEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_callback_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveEventResponse.ProtoReflect.Descriptor instead.
func (*ActiveEventResponse) Descriptor() ([]byte, []int) {
	return file_callback_service_proto_rawDescGZIP(), []int{9}
}

func (x *ActiveEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActiveEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 框架退出事件
type FrameExitEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallbackId uint32 `protobuf:"varint,1,opt,name=callback_id,json=callbackId,proto3" json:"callback_id,omitempty"`
}

func (x *FrameExitEventRequest) Reset() {
	*x = FrameExitEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrameExitEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameExitEventRequest) ProtoMessage() {}

func (x *FrameExitEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callback_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameExitEventRequest.ProtoReflect.Descriptor instead.
func (*FrameExitEventRequest) Descriptor() ([]byte, []int) {
	return file_callback_service_proto_rawDescGZIP(), []int{10}
}

func (x *FrameExitEventRequest) GetCallbackId() uint32 {
	if x != nil {
		return x.CallbackId
	}
	return 0
}

type FrameExitEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *FrameExitEventResponse) Reset() {
	*x = FrameExitEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrameExitEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameExitEventResponse) ProtoMessage() {}

func (x *FrameExitEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_callback_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameExitEventResponse.ProtoReflect.Descriptor instead.
func (*FrameExitEventResponse) Descriptor() ([]byte, []int) {
	return file_callback_service_proto_rawDescGZIP(), []int{11}
}

func (x *FrameExitEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 广播事件
type BroadcastEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallbackId uint32 `protobuf:"varint,1,opt,name=callback_id,json=callbackId,proto3" json:"callback_id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data       []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON-encoded map[string]interface{}
}

func (x *BroadcastEventRequest) Reset() {
	*x = BroadcastEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastEventRequest) ProtoMessage() {}

func (x *BroadcastEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callback_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastEventRequest.ProtoReflect.Descriptor instead.
func (*BroadcastEventRequest) Descriptor() ([]byte, []int) {
	return file_callback_service_proto_rawDescGZIP(), []int{12}
}

func (x *BroadcastEventRequest) GetCallbackId() uint32 {
	if x != nil {
		return x.CallbackId
	}
	return 0
}

func (x *BroadcastEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BroadcastEventRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BroadcastEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // JSON-encoded interface{}
}

func (x *BroadcastEventResponse) Reset() {
	*x = BroadcastEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastEventResponse) ProtoMessage() {}

func (x *BroadcastEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_callback_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastEventResponse.ProtoReflect.Descriptor instead.
func (*BroadcastEventResponse) Descriptor() ([]byte, []int) {
	return file_callback_service_proto_rawDescGZIP(), []int{13}
}

func (x *BroadcastEventResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

// 控制台命令
type ConsoleCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallbackId uint32   `protobuf:"varint,1,opt,name=callback_id,json=callbackId,proto3" json:"callback_id,omitempty"`
	Args       []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *ConsoleCommandRequest) Reset() {
	*x = ConsoleCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsoleCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleCommandRequest) ProtoMessage() {}

func (x *ConsoleCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callback_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleCommandRequest.ProtoReflect.Descriptor instead.
func (*ConsoleCommandRequest) Descriptor() ([]byte, []int) {
	return file_callback_service_proto_rawDescGZIP(), []int{14}
}

func (x *ConsoleCommandRequest) GetCallbackId() uint32 {
	if x != nil {
		return x.CallbackId
	}
	return 0
}

func (x *ConsoleCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type ConsoleCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ConsoleCommandResponse) Reset() {
	*x = ConsoleCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsoleCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleCommandResponse) ProtoMessage() {}

func (x *ConsoleCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_callback_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleCommandResponse.ProtoReflect.Descriptor instead.
func (*ConsoleCommandResponse) Descriptor() ([]byte, []int) {
	return file_callback_service_proto_rawDescGZIP(), []int{15}
}

func (x *ConsoleCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsoleCommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_callback_service_proto protoreflect.FileDescriptor

var file_callback_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x64, 0x6b, 0x22, 0x65, 0x0a,
	0x10, 0x43, 0x68, 0x61, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x2b, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x74, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x63, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x22, 0x50, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x61,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x61, 0x77, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x61, 0x77, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x2f, 0x0a, 0x13, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x73, 0x0a, 0x12, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0a, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x2f, 0x0a, 0x13, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x36, 0x0a, 0x13, 0x50, 0x72,
	0x65, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x49, 0x64, 0x22, 0x46, 0x0a, 0x14, 0x50, 0x72, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x35, 0x0a, 0x12, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x49,
	0x64, 0x22, 0x45, 0x0a, 0x13, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x38, 0x0a, 0x15, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x45, 0x78, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x49, 0x64, 0x22, 0x32, 0x0a, 0x16, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x45, 0x78, 0x69, 0x74, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x60, 0x0a, 0x15, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63,
	0x61, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x30, 0x0a, 0x16, 0x42, 0x72, 0x6f, 0x61,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4c, 0x0a, 0x15, 0x43, 0x6f,
	0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x48, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x73,
	0x6f, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x32, 0x96, 0x05, 0x0a, 0x0f, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x4f, 0x6e, 0x43, 0x68, 0x61, 0x74,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73,
	0x64, 0x6b, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x11, 0x4f, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x4a, 0x6f, 0x69, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x2e, 0x73, 0x64, 0x6b, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x12,
	0x4f, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x17, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x64,
	0x6b, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0d, 0x4f, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0e, 0x4f, 0x6e, 0x50,
	0x72, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x2e, 0x73, 0x64,
	0x6b, 0x2e, 0x50, 0x72, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x50, 0x72, 0x65, 0x6c,
	0x6f, 0x61, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x42, 0x0a, 0x0d, 0x4f, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x17, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x64, 0x6b,
	0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x10, 0x4f, 0x6e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x45,
	0x78, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x46,
	0x72, 0x61, 0x6d, 0x65, 0x45, 0x78, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x45, 0x78, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4b, 0x0a, 0x10, 0x4f, 0x6e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x42, 0x72, 0x6f, 0x61,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b,
	0x0a, 0x10, 0x4f, 0x6e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x1a, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x24, 0x5a, 0x22, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x6f, 0x71, 0x69, 0x6a,
	0x69, 0x65, 0x2f, 0x46, 0x49, 0x4e, 0x2d, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x73, 0x64,
	0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_callback_service_proto_rawDescOnce sync.Once
	file_callback_service_proto_rawDescData = file_callback_service_proto_rawDesc
)

func file_callback_service_proto_rawDescGZIP() []byte {
	file_callback_service_proto_rawDescOnce.Do(func() {
		file_callback_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_callback_service_proto_rawDescData)
	})
	return file_callback_service_proto_rawDescData
}

var file_callback_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_callback_service_proto_goTypes = []interface{}{
	(*ChatEventRequest)(nil),       // 0: sdk.ChatEventRequest
	(*ChatEventResponse)(nil),      // 1: sdk.ChatEventResponse
	(*PlayerEventRequest)(nil),     // 2: sdk.PlayerEventRequest
	(*PlayerEventResponse)(nil),    // 3: sdk.PlayerEventResponse
	(*PacketEventRequest)(nil),     // 4: sdk.PacketEventRequest
	(*PacketEventResponse)(nil),    // 5: sdk.PacketEventResponse
	(*PreloadEventRequest)(nil),    // 6: sdk.PreloadEventRequest
	(*PreloadEventResponse)(nil),   // 7: sdk.PreloadEventResponse
	(*ActiveEventRequest)(nil),     // 8: sdk.ActiveEventRequest
	(*ActiveEventResponse)(nil),    // 9: sdk.ActiveEventResponse
	(*FrameExitEventRequest)(nil),  // 10: sdk.FrameExitEventRequest
	(*FrameExitEventResponse)(nil), // 11: sdk.FrameExitEventResponse
	(*BroadcastEventRequest)(nil),  // 12: sdk.BroadcastEventRequest
	(*BroadcastEventResponse)(nil), // 13: sdk.BroadcastEventResponse
	(*ConsoleCommandRequest)(nil),  // 14: sdk.ConsoleCommandRequest
	(*ConsoleCommandResponse)(nil), // 15: sdk.ConsoleCommandResponse
}
var file_callback_service_proto_depIdxs = []int32{
	0,  // 0: sdk.CallbackService.OnChatEvent:input_type -> sdk.ChatEventRequest
	2,  // 1: sdk.CallbackService.OnPlayerJoinEvent:input_type -> sdk.PlayerEventRequest
	2,  // 2: sdk.CallbackService.OnPlayerLeaveEvent:input_type -> sdk.PlayerEventRequest
	4,  // 3: sdk.CallbackService.OnPacketEvent:input_type -> sdk.PacketEventRequest
	6,  // 4: sdk.CallbackService.OnPreloadEvent:input_type -> sdk.PreloadEventRequest
	8,  // 5: sdk.CallbackService.OnActiveEvent:input_type -> sdk.ActiveEventRequest
	10, // 6: sdk.CallbackService.OnFrameExitEvent:input_type -> sdk.FrameExitEventRequest
	12, // 7: sdk.CallbackService.OnBroadcastEvent:input_type -> sdk.BroadcastEventRequest
	14, // 8: sdk.CallbackService.OnConsoleCommand:input_type -> sdk.ConsoleCommandRequest
	1,  // 9: sdk.CallbackService.OnChatEvent:output_type -> sdk.ChatEventResponse
	3,  // 10: sdk.CallbackService.OnPlayerJoinEvent:output_type -> sdk.PlayerEventResponse
	3,  // 11: sdk.CallbackService.OnPlayerLeaveEvent:output_type -> sdk.PlayerEventResponse
	5,  // 12: sdk.CallbackService.OnPacketEvent:output_type -> sdk.PacketEventResponse
	7,  // 13: sdk.CallbackService.OnPreloadEvent:output_type -> sdk.PreloadEventResponse
	9,  // 14: sdk.CallbackService.OnActiveEvent:output_type -> sdk.ActiveEventResponse
	11, // 15: sdk.CallbackService.OnFrameExitEvent:output_type -> sdk.FrameExitEventResponse
	13, // 16: sdk.CallbackService.OnBroadcastEvent:output_type -> sdk.BroadcastEventResponse
	15, // 17: sdk.CallbackService.OnConsoleCommand:output_type -> sdk.ConsoleCommandResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_callback_service_proto_init() }
func file_callback_service_proto_init() {
	if File_callback_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_callback_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreloadEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreloadEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActiveEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActiveEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FrameExitEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FrameExitEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsoleCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsoleCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_callback_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_callback_service_proto_goTypes,
		DependencyIndexes: file_callback_service_proto_depIdxs,
		MessageInfos:      file_callback_service_proto_msgTypes,
	}.Build()
	File_callback_service_proto = out.File
	file_callback_service_proto_rawDesc = nil
	file_callback_service_proto_goTypes = nil
	file_callback_service_proto_depIdxs = nil
}
